"""
Kinexica — Carbon Credit & MRV Agent
Calculates verifiable carbon credits from food waste prevented,
generates Measurement-Reporting-Verification (MRV) records,
and prepares them for blockchain stamping.
"""
# pylint: disable=import-error
from crewai import Agent, Task, LLM


def get_carbon_agent(llm: LLM) -> Agent:
    return Agent(
        role="Carbon Credit & MRV Specialist",
        goal=(
            "Calculate the exact carbon credits generated by preventing food spoilage "
            "and produce a verifiable MRV record compliant with Verra VCS and Gold Standard."
        ),
        backstory=(
            "You are a certified carbon accountant and Life Cycle Assessment (LCA) expert "
            "with deep expertise in food supply chain emissions. You know that 1 kg of "
            "prevented tomato waste saves approximately 2.09 kgCO₂e (WRAP UK methodology). "
            "You generate MRV records that are stamped on-chain for tamper-proof carbon markets."
        ),
        verbose=True,
        allow_delegation=False,
        llm=llm,
    )


def get_carbon_task(agent: Agent, payload: dict) -> Task:
    kg_saved = payload.get("kg_saved", 0.0)
    asset_id = payload.get("asset_id", "unknown")
    commodity = payload.get("commodity", "produce")
    # WRAP UK: tomatoes ≈ 2.09 kgCO₂e/kg, avg mixed produce ≈ 1.8 kgCO₂e/kg
    emission_factor = payload.get("emission_factor_kgco2e_per_kg", 1.80)
    credits = round(kg_saved * emission_factor / 1000, 6)   # tCO₂e

    return Task(
        description=(
            f"Asset: {asset_id}  |  Commodity: {commodity}  |  "
            f"Kg Prevented: {kg_saved}  |  Emission Factor: {emission_factor} kgCO₂e/kg\n\n"
            f"Estimated credits: {credits} tCO₂e (preliminary).\n\n"
            "Tasks:\n"
            "1. Validate emissions factor against IPCC AR6 Table 7.SM.8 and WRAP food waste database.\n"
            "2. Produce a complete MRV record in structured JSON format:\n"
            "   - asset_id, commodity, kg_saved, emission_factor, tco2e_credits\n"
            "   - methodology: 'WRAP-UK v3.0 / VCS VM0042'\n"
            "   - verification_status: 'Pending Blockchain Stamp'\n"
            "   - timestamp\n"
            "3. Flag if credits exceed 1 tCO₂e (Gold Standard minimum issuance threshold).\n"
            "4. Recommend marketplace: Toucan Protocol, Moss.Earth, or KlimaDAO integration."
        ),
        expected_output=(
            "A structured MRV JSON record with tCO₂e credits, methodology citation, "
            "and marketplace recommendation."
        ),
        agent=agent,
    )
