"""
SpoilSense Edge Client: Real-time UI dashboard rendered using Flet.
"""

import asyncio
import os

import requests
import flet as ft

# FOSS Tunnel Gateway URL:
# Replace this with the URL generated by localtunnel or zrok before packaging the APK.
API_BASE_URL = os.getenv("API_BASE_URL", "http://127.0.0.1:8000")


def main(page: ft.Page):  # pylint: disable=too-many-statements,too-many-nested-blocks
    """
    Main entry point for the Flet UI. Handles rendering and async event polling.
    """
    page.title = "SpoilSense Edge Client"
    page.theme_mode = ft.ThemeMode.DARK
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.scroll = ft.ScrollMode.ADAPTIVE

    # UI Elements with explicit properties rather than kwargs (pleases aggressive linters)
    # type: ignore # pylint: disable=too-many-function-args
    title = ft.Text("SpoilSense Telemetry")
    title.size = 24
    title.weight = ft.FontWeight.BOLD

    # type: ignore # pylint: disable=too-many-function-args
    asset_id_text = ft.Text("Asset ID: ---")
    asset_id_text.size = 16

    # type: ignore # pylint: disable=too-many-function-args
    temp_text = ft.Text("Temp: -- °C")
    temp_text.size = 16

    # type: ignore # pylint: disable=too-many-function-args
    ethylene_text = ft.Text("Ethylene: -- ppm")
    ethylene_text.size = 16

    # type: ignore # pylint: disable=too-many-function-args
    shelf_life_text = ft.Text("Est. Shelf Life: -- h")
    shelf_life_text.size = 16

    # Status Card
    # type: ignore # pylint: disable=too-many-function-args
    status_text = ft.Text("Status: UNKNOWN")
    status_text.size = 20
    status_text.weight = ft.FontWeight.BOLD

    # Golden Blockchain Receipt text
    # type: ignore # pylint: disable=too-many-function-args
    tx_hash_text = ft.Text("")
    tx_hash_text.size = 14
    tx_hash_text.weight = ft.FontWeight.BOLD
    tx_hash_text.color = ft.colors.YELLOW_200
    tx_hash_text.visible = False

    col = ft.Column([asset_id_text, temp_text,
                     # type: ignore # pylint: disable=too-many-function-args
                     ethylene_text, shelf_life_text, status_text, tx_hash_text])
    col.alignment = ft.MainAxisAlignment.CENTER

    # type: ignore # pylint: disable=too-many-function-args
    status_card = ft.Container(col)
    status_card.width = 300
    status_card.height = 200
    status_card.bgcolor = ft.colors.GREY_800
    status_card.border_radius = 15
    status_card.padding = 20
    status_card.alignment = ft.Alignment(0, 0)
    status_card.animate = ft.animation.Animation(
        500, ft.AnimationCurve.EASE_OUT)

    async def poll_backend():
        is_flashing = False
        while True:
            try:
                # Command Flet to continuously poll public Localtunnel URL
                res = requests.get(
                    f"{API_BASE_URL}/asset/Pallet-4B-Tomatoes", timeout=2)

                if res.status_code == 200:
                    data = res.json()

                    if "error" not in data:
                        asset_id_text.value = f"Asset ID: {data['asset_id']}"
                        temp_text.value = f"Temp: {data['current_temp_c']} °C"
                        ethylene_text.value = f"Ethylene: {data['ethylene_ppm']} ppm"
                        sl_f = data['estimated_shelf_life_h']
                        shelf_life_text.value = f"Est. Shelf Life: {sl_f:.2f} h"

                        status = data['status']
                        status_text.value = f"Status: {status.upper()}"

                        if status == "Stable":
                            status_card.bgcolor = ft.colors.GREEN_700
                            is_flashing = False
                            tx_hash_text.visible = False

                        elif status == "Liquidated" and data.get("tx_hash"):
                            # Block-verified Immutable Drop
                            status_card.bgcolor = ft.colors.AMBER_600
                            is_flashing = False
                            tx_hash_text.value = f"TxHash: {data['tx_hash'][:10]}... | Block: {data['block_number']}"
                            tx_hash_text.visible = True
                            status_text.value = "Status: IMMUTABLE CONTRACT SECURED"

                        elif status in ("Distressed", "Liquidated"):
                            # Flashing Red Effect before transaction clears
                            is_flashing = not is_flashing
                            if is_flashing:
                                status_card.bgcolor = ft.colors.RED_900
                            else:
                                status_card.bgcolor = ft.colors.RED_500
                    else:
                        status_text.value = "Status: NOT FOUND"
                else:
                    status_text.value = "Status: OFFLINE"
            except requests.exceptions.RequestException:
                status_text.value = "Error: Cannot reach Hub"
                status_card.bgcolor = ft.colors.GREY_800

            page.update()
            await asyncio.sleep(1.0)  # Poll every second

    def start_monitoring(_):
        try:
            requests.post(f"{API_BASE_URL}/start-monitoring", timeout=2)
            # type: ignore # pylint: disable=too-many-function-args
            page.snack_bar = ft.SnackBar(ft.Text("Monitor triggered."))
            page.snack_bar.open = True
        except requests.exceptions.RequestException:
            # type: ignore # pylint: disable=too-many-function-args
            snack_txt = ft.Text("Failed to trigger monitor. Check gateway.")
            # type: ignore # pylint: disable=too-many-function-args
            page.snack_bar = ft.SnackBar(snack_txt)
            page.snack_bar.open = True
        page.update()

    # type: ignore # pylint: disable=too-many-function-args
    trigger_btn = ft.ElevatedButton("Start Monitoring Loop")
    trigger_btn.on_click = start_monitoring
    trigger_btn.bgcolor = ft.colors.BLUE_700
    trigger_btn.color = ft.colors.WHITE

    page.add(title, status_card, trigger_btn)

    # Start polling loop
    page.run_task(poll_backend)


if __name__ == "__main__":
    ft.app(target=main)
